export default {
    ADMIN_ERROR: 'ADMIN_ERROR',

    GET_ALL_USER: "GET_ALL_USERS",
    BAN_USER_BY_ID: "BAN_USER_BY_ID",
    ALL_USERS: 'ALL_USERS',

    GET_ALL_ENTRIES: "GET_ALL_USERS",
    UPDATE_VALIDITY_OF_ENTRY: 'UPDATE_VALIDITY_OF_ENTRY',
    ALL_ENTRIES: 'ALL_ENTRIES',
};
