export default {
    CHAT_ERROR: "CHAT_ERROR",
    CLOSE_OR_OPEN_CHAT: "CLOSE_OR_OPEN_CHAT",
    CLOSE_OR_OPEN_CONNECTION: 'CLOSE_OR_OPEN_CONNECTION',

    TO_FIND_USERS_STAGE: "TO_FIND_USERS_STAGE",
    TO_CLOSE_FIND_USERS_STAGE: "TO_CLOSE_FIND_USERS_STAGE",
    CLEAR_FOUND_USERS: "CLEAR_FOUND_USERS",

    TO_NEXT_CHAT_STAGE: "TO_NEXT_CHAT_STAGE",

    CLEAR_MESSAGES: 'CLEAR_MESSAGES',

    PARTICIPANT_START_TYPING: "PARTICIPANT_START_TYPING",
    PARTICIPANT_STOP_TYPING: "PARTICIPANT_STOP_TYPING",

    ADD_NEW_CONVERSATION: "ADD_NEW_CONVERSATION",
    ADD_CONVERSATION: "ADD_CONVERSATION",

    FOUND_USERS: 'FOUND_USERS',

    OPEN_CONVERSATION: "OPEN_CONVERSATION",
    CLOSE_CONVERSATION: 'CLOSE_CONVERSATION',

    SHOW_CONVERSATIONS: 'SHOW_CONVERSATIONS',

    ADD_MESSAGES: "ADD_MESSAGES",
    NEW_MESSAGE: "NEW_MESSAGE",
};
