export default {
    CHAT_ERROR: "CHAT_ERROR",
    CLOSE_OR_OPEN_CHAT: "CLOSE_OR_OPEN_CHAT",
    CLOSE_OR_OPEN_CONNECTION: 'CLOSE_OR_OPEN_CONNECTION',

    CLEAR_STORE: 'CLEAR_STORE',  //?

    TO_FIND_USERS_STAGE: "TO_FIND_USERS_STAGE", // +
    TO_CLOSE_FIND_USERS_STAGE: "TO_CLOSE_FIND_USERS_STAGE", // +
    CLEAR_FOUND_USERS: "CLEAR_FOUND_USERS", // +

    TO_NEXT_CHAT_STAGE: "TO_NEXT_CHAT_STAGE", // +

    SEARCH_USERS: "SEARCH_USERS",
    FOUND_USERS: 'FOUND_USERS',

    OPEN_CONVERSATION: "OPEN_CONVERSATION",
    CLOSE_CONVERSATION: 'CLOSE_CONVERSATION',

    SHOW_CONVERSATIONS: 'SHOW_CONVERSATIONS',

    NEW_MESSAGE: "NEW_MESSAGE",
    ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE",
};
