export default {
    DASHBOARD_ERROR: "DASHBOARD_ERROR",

    CLOSE_OR_OPEN_SIDE_MENU: "CLOSE_OR_OPEN_SIDE_MENU",

    USER_CONTESTS: "USER_CONTESTS",
    GET_USER_CONTESTS: "GET_USER_CONTESTS",

    CONTEST_BY_ID: "CONTEST_BY_ID",
    GET_CONTEST_BY_ID: "GET_CONTEST_BY_ID",


    USER_ENTRIES: 'USER_ENTRIES',
    ENTRIES_BY_ID: 'ENTRIES_BY_ID',
    GET_ENTRIES_BY_ID: "GET_ENTRIES_BY_ID",
    GET_USER_ENTRIES: "GET_USER_ENTRIES",

    CREATE_ENTRY: 'CREATE_ENTRY',

    UPDATE_ENTRY_BY_ID: 'UPDATE_ENTRY_BY_ID',
    LIKE_ENTRY_BY_ID: 'LIKE_ENTRY_BY_ID',

    FOUND_CONTESTS: "FOUND_CONTESTS",
    FIND_CONTESTS_BY_PARAMS: 'FIND_CONTESTS_BY_PARAMS'
};
