export default {
  USERS_REQUEST: 'USERS_REQUEST',
  USERS_RESPONSE: 'USERS_RESPONSE',
  USERS_ERROR: 'USERS_ERROR',
  
  CREATE_USER: 'CREATE_USER',
  GET_USER: "GET_USER",
  LOGIN_USER: 'LOGIN_USER',
  USER_LOGOUT: "USER_LOGOUT",

  GET_ALL_USER: "GET_ALL_USERS",
  BAN_USER_BY_ID: "BAN_USER_BY_ID",


  SAVE_TOKENS_LOCALLY: "SAVE_TOKENS_LOCALLY",
  TOKENS_ERROR: "TOKENS_ERROR",

  CREATE_CONTEST: "CREATE_CONTEST",
  NEXT_STAGE_CONTEST: "NEXT_STAGE_CONTEST",
  PREV_STAGE_CONTEST: "PREV_STAGE_CONTEST",
  STAGE_CONTEST: "STAGE_CONTEST",

  ADD_TO_CONTEST_QUEUE: "TO_CONTEST_QUEUE",
  WRITE_CONTEST_FORM_DATA: "WRITE_CONTEST_FORM_DATA",
  WRITE_FORM_DATA_TO_STORE: "WRITE_FORM_DATA_TO_STORE",

  GET_PRICE_OF_CONTEST: "GET_PRICE_OF_CONTEST",
  WRITE_PRICE_OF_CONTEST: "WRITE_PRICE_OF_CONTEST",

  CHAT_ERROR: "CHAT_ERROR",
  CLOSE_OR_OPEN_CHAT: "CLOSE_OR_OPEN_CHAT",
  CLOSE_OR_OPEN_CONNECTION: "CLOSE_OR_OPEN_CONNECTION",
  SEARCH_USERS: "SEARCH_USERS",
};
